# Default values for zeebe-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: 
  elasticsearch:
    host: "elasticsearch-master"
    port: 9200 
  zeebe: "{{ .Release.Name }}-zeebe"

clusterSize: "3"
partitionCount: "3"
replicationFactor: "3"
cpuThreadCount: "2"
ioThreadCount: "2"
pvcSize: "5Gi"

elasticsearch:
  enabled: true
  imageTag: 6.8.1
kibana:
  enabled: false
  imageTag: 6.8.1

JavaOpts: |
  -XX:+UseParallelGC 
  -XX:MinHeapFreeRatio=5
  -XX:MaxHeapFreeRatio=10 
  -XX:GCTimeRatio=4 
  -XX:AdaptiveSizePolicyWeight=90
  -XX:+PrintFlagsFinal
image:
  repository: camunda/zeebe
  tag: 0.21.1
  pullPolicy: IfNotPresent
labels:
  app: zeebe
service:
  type: ClusterIP
  http:
    port: 9600
  gateway:
    port: 26500
  command:
    port: 26501  
  internal:
    port: 26502
resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
