apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ tpl .Values.global.zeebe . | quote }}
  labels:
{{- toYaml  .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.clusterSize  }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ tpl .Values.global.zeebe . | quote }}
  serviceName: {{ tpl .Values.global.zeebe . | quote }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ tpl .Values.global.zeebe . | quote }}
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.check_names: '["openmetrics"]'
        ad.datadoghq.com/{{ .Chart.Name }}.init_configs: '[{}]'
        ad.datadoghq.com/{{ .Chart.Name }}.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:9600/metrics",
              "namespace":"zeebe.prometheus",
              "metrics": [{"zeebe_*":"zeebe", "process_*":"process"}]
            }
          ]
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ZEEBE_LOG_LEVEL
          value: debug
        - name: ZEEBE_PARTITIONS_COUNT
          value: {{ .Values.partitionCount | quote }}
        - name: ZEEBE_CLUSTER_SIZE
          value: {{ .Values.clusterSize | quote }}
        - name: ZEEBE_REPLICATION_FACTOR
          value: {{ .Values.replicationFactor | quote }}
        - name: JAVA_TOOL_OPTIONS
          value: 
           {{- toYaml .Values.JavaOpts | nindent 12}}
        ports:
        - containerPort: 9600
          name: http
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: internal
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
          subPath: zeebe.cfg.toml
        - name: config
          mountPath: /usr/local/bin/startup.sh
          subPath: startup.sh
        - name: data
          mountPath: /usr/local/zeebe/data
      volumes:
      - name: config
        configMap:
          name: {{ tpl .Values.global.zeebe . | quote }}
          defaultMode: 0744
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.pvcSize | quote }}

